### ISSUE TITLE
Sync this project with Stripes...

### ISSUE THREAD

**Issue by lookfirst** [bendrucker/creditcards-types#5]
https://github.com/stripe/jquery.payment/blob/master/src/jquery.payment.coffee

There is a whole list of cc's and regex's that are different in there than what you have. 

I trust stripe to have the correct values more than I trust you to have them. 

Will you either make the changes or accept PR's for that?

**Comment by bendrucker** [comment]
> I trust stripe to have the correct values more than I trust you to have them.

That's a pretty rude thing to say. Please keep these conversations positive.

I've communicated with Stripe engineers about backing jquery.payments with creditcards but we haven't made any concrete progress yet. The unit tests are quite complete. 

I will take PRs that improve the regular expressions with accompanying tests. I will not take ones that simply overwrite things with values from jquery.payments since the regexes here are the result of more research and an effort to avoid collisions.

**Comment by lookfirst** [comment]
Not trying to be rude, just being factual. Don't take it personally.
