### ISSUE TITLE
Failing to Distinguish Between Maestro and Discover Card Numbers

### ISSUE THREAD

**Issue by waleedshkt** [bendrucker/creditcards-types#78]
Currently using Checkout.com Frames components for React Native app, and it has been found that Frames is using this package to determine card type.

I'm sure this package together with `creditcards` is immensely supporting the rapid development of many other software. But there's this discrepancy arises which I noticed that when one tries to add Discover card number this package detects Maestro instead. Here's a [link](https://github.com/checkout/frames-react-native/issues/7#issue-1135797218) to this issue.

I surmise this is perhaps due to some cards updating their identifiers recently and this package's detection algorithm is not yet updated to take those changes into account?

**Comment by bendrucker** [comment]
The number in question is mentioned right in the readme as well as multiple existing issues (https://github.com/bendrucker/creditcards-types/issues/54, https://github.com/bendrucker/creditcards-types/issues/28):

https://github.com/bendrucker/creditcards-types#test-card-numbers

The ranges here reflect available [documentation](https://github.com/bendrucker/creditcards-types/tree/master/docs), preferably from the card issuer itself where available. 

Test cards vary by payment provider, with some common ones and others that vary. To the extent that test cards depart from the officially documented ranges, it is the user's responsibility to add a custom type and prepend it.

In the case of a commercial SDK using that package, the vendor should handle this on behalf of their users, since they know all of their test cards. Their test suite should probably also confirm that those numbers are parsed as the expected type.

**Comment by waleedshkt** [comment]
Thank you for updating
