### ISSUE TITLE
Add support for Aura, Elo, and Hipercard

### ISSUE THREAD

**Issue by cybercyst** [bendrucker/creditcards-types#9]
Here are the validation rules for all three types!
https://developers.ebanx.com/api-reference/validation-rules

**Comment by bendrucker** [comment]
Much appreciated, working on this now

**Comment by bendrucker** [comment]
Need to think a bit on the best API to handle this. I can support these but because of the unusual ranges it would make the library worse for the majority of users who take more common card brands. I'll figure something out but it may take me a bit to make it available on the Angular side.

**Comment by sullivanpt** [comment]
@bendrucker can you elaborate on the integration problems faced here? I don't use the angular piece, but I'd love to help with a PR.

**Comment by bendrucker** [comment]
These card providers don't document their ranges anywhere publicly that I've found. And from the test numbers I've seen they are tiny ranges that collide with major card issuers. That combination makes them super hard to support.

**Comment by bendrucker** [comment]
I'm going to close this out since I don't plan to work on it now. Someone recently added Elo support to jquery.payment: 

https://github.com/stripe/jquery.payment/issues/221

The range size is quite large and I'd have to make some changes to the library to:

* Make the type optional and not included by default
* Allow the type to be added with the correct priority so it matches ahead of the Visa/MC ranges it occupies

I'd consider doing this in one fell swoop for Aura/Elo/Hipercard but not individually.

And I'd still need official documentation for Aura and Hipercard. That's my current blocker. If someone gets in touch with both companies and gets me an official doc or even an email reply I can make some time to implement the regexes and APIs needed.
